In [1]:
# demonstrate the types of feature created
from numpy import asarray
from sklearn.preprocessing import PolynomialFeatures

In [2]:
# define the data set
data = asarray([[2,3],[2,3],[2,3]])
print(data)

[[2 3]
 [2 3]
 [2 3]]


In [3]:
# perform a polynominal features transform of the data set
trans = PolynomialFeatures(degree=2)
data = trans.fit_transform(data)
print(data)

[[1. 2. 3. 4. 6. 9.]
 [1. 2. 3. 4. 6. 9.]
 [1. 2. 3. 4. 6. 9.]]
